language: node_js
sudo: required
node_js:
  - 8.11.3
branch: master
cache:
  directories:
    - node_modules
  yarn: true
install:
  - yarn
before_install:
  - export TZ='Asia/Shanghai'  # 设置时区
  - chmod +x deploy.sh
script:
  - bash ./deploy.sh